// Available subsection list for AI.js: ['General', 'Machine Learning']
// Available tags list for AI.js: ['models', 'algorithms', 'research', 'tools', 'code']

const ai = {
  name: 'AI',
  icon: '/resources/ai.svg',
  resources: [
    {
      title: 'ChatGPT',
      link: 'https://chat.openai.com/',
      description: 'An AI language model that assists with various queries.',
      imageUrl: 'https://openai.com/favicon.ico',
      dateAdded: '2024-10-09',
      level: 'any',
      subsection: 'General',
      tags: ['models', 'tools', 'research'],
    },
    {
      title: 'shadcn/ui',
      link: 'https://ui.shadcn.dev/',
      description: 'A beautiful, accessible component library for building UIs, particularly useful in AI/ML applications.',
      imageUrl: 'https://ui.shadcn.dev/favicon.ico',
      dateAdded: '2024-10-12',
      level: 'any',
      subsection: 'General',
      tags: ['tools', 'code'],
    },
    {
      title: 'Perplexity AI',
      link: 'https://www.perplexity.ai',
      description: 'A free AI-powered answer engine that provides accurate, trusted, and real-time answers to any question.',
      imageUrl: 'https://framerusercontent.com/images/TPDRRsckgte6GnPC4QZSWbDvA.svg', 
      dateAdded: '2024-11-11',
      level: 'any',
      subsection: 'General',
      tags: ['tools', 'research'],
    },
    {
      title: 'Grammarly',
      link: 'https://www.grammarly.com/',
      description: 'An AI-powered writing assistant that helps improve grammar, spelling, punctuation, and style in real-time.',
      imageUrl: 'https://static-web.grammarly.com/cms/master/public/favicon.ico',
      dateAdded: '2025-01-04',
      level: 'any',
      subsection: 'General',
      tags: ['tools', 'models'],
    },
    {
      title: 'DeepSeek',
      link: 'https://chat.deepseek.com',
      description: 'Advanced AI models specializing in complex reasoning tasks for science, coding, and mathematics.',
      imageUrl: 'https://chat.deepseek.com/favicon.svg',
      dateAdded: '2025-02-01',
      level: 'any',
      subsection: 'General',
      tags: ['models', 'tools', 'research'],
    },
    {
      title: 'Cursor AI',
      link: 'https://www.cursor.com/',
      description: 'An AI-powered coding assistant designed to enhance developer productivity.',
      imageUrl: 'https://www.cursor.com/favicon.ico',
      dateAdded: '2025-05-06',
      level: 'any',
      subsection: 'General',
      tags: ['tools', 'code'],
    },
    {
      title: 'Claude AI',
      link: 'https://claude.ai',
      description: 'Anthropic’s conversational AI assistant designed for thoughtful, safe, and high-quality interactions.',
      imageUrl: 'https://claude.ai/favicon.ico',
      dateAdded: '2025-09-18',
      level: 'any',
      subsection: 'General',
      tags: ['models', 'tools', 'research'],
    },
  ],
};

export default ai;
